services:
  # Bad attempt to run client with docker;
  # you can delete comment lines below:
  #
  # client:
  #   container_name: client
  #   restart: "no"
  #   build:
  #     context: ./client
  #     dockerfile: "Dockerfile"
  #   environment:
  #     HOST: server
  #     PORT: 5000
  #   networks:
  #     - server.network
  #   logging:
  #     options:
  #       max-size: "100m"
  #   depends_on:
  #     server:
  #       condition: service_started   
  
  server:
    container_name: server
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:5000:5000"
    build:
      context: ./server
      dockerfile: "Dockerfile"
    env_file:
      - .env
    volumes:
      - ./server/templates:/app/templates:ro
      - ./server/static:/app/static:ro
    networks:
      - server.network

networks:
  server.network: {}
