[package]
name = "get_video_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
tokio = {version = "1.39.2", features = ["rt-multi-thread", "macros"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
